### ISSUE TITLE
Spell checking in Markdown cells

### ISSUE THREAD

**Issue by godaygo** [nteract/archived-desktop-app#2555] opened 2018-02-20 08:29 UTC
To begin with - Thank you! Very cool project and it's great to see that with every release it becomes more mature. One feature which I'm missing is a spell checking functionality in Markdown cells, will you consider  or do you have plans to add such a feature? I've searched through issues, but didn't find any related.

**Comment by rgbkrk** [comment] 2018-02-20 08:56
Thanks! This is a duplicate of https://github.com/nteract/nteract/issues/1116. While we know about it no one is working on it or has plans to, though it's deemed possible by the lead author / maintainer of CodeMirror (the editor we use underneath).

**Closed as completed** 2018-02-20 08:56 UTC
