### ISSUE TITLE
Add "Open Recent" menu in File menu.

### ISSUE THREAD

**Issue by Jaykul** [nteract/archived-desktop-app#1795] opened 2017-07-21 01:43 UTC
Since there's no root window like Jupyter has, it sure would be nice to have nteract remember my most recent notebooks -- I mean, the example notebooks are neat, but only for the first day or two ;-)

You know, like this one:
![image](https://user-images.githubusercontent.com/192942/28445702-1a60f6da-6d94-11e7-937f-137ff7b6b211.png)

**Comment by dhirschfeld** [comment] 2017-07-21 07:10
**xref:** #263

**Comment by rgbkrk** [comment] 2017-08-10 21:03
Closing as dupe of #263, totally agree we need this. :smile:

**Closed as completed by rgbkrk** 2017-08-10 21:03 UTC
