### ISSUE TITLE
png image now shown

### ISSUE THREAD

**Issue by amueller** [nteract/archived-desktop-app#1556] opened 2017-03-16 17:17 UTC
I have a markdown cell with
```
![sepal_petal](images/iris_petal_sepal.png)
```
but it doesn't render.

![image](https://cloud.githubusercontent.com/assets/449558/24009239/bd7283fa-0a4a-11e7-90c9-1b30077dc4b4.png)

 I imagine something is wrong with the path? But the file is there:
![image](https://cloud.githubusercontent.com/assets/449558/24009306/f1f389f8-0a4a-11e7-84d9-7afa797e2153.png)

**Comment by jdetle** [comment] 2017-03-16 17:41
This seems to be a problem with how the file path is getting resolved. Definitely a bug in the dev install, not sure yet if it is the same in the distribution.

**Comment by rgbkrk** [comment] 2017-03-16 17:46
Duplicate of #1242. There's also an open PR that attempted to fix it in #1432.

My main suggestion in the issues related to this is to use [the `<base>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) to allow resolving relative files. The reason they don't display is that the "location" of the browser is our `index.html` inside the package.

**Closed as completed** 2017-03-16 17:46 UTC

**Comment by rgbkrk** [comment] 2017-03-16 17:48
More refactoring would need to be done, here's a good start @jdetle: https://github.com/nteract/nteract/issues/349#issuecomment-278180910

**Comment by jdetle** [comment] 2017-03-16 17:55
Thanks!
