### ISSUE TITLE
Unable to run on Windows

### ISSUE THREAD

**Issue by klonuo** [nteract/archived-desktop-app#388] opened 2016-04-23 23:51 UTC
Is this supposed to be run under Windows?

After installing I get this:

```
D:\src\nteract>npm run start

> nteract@0.0.1 prestart D:\src\nteract
> npm run build

> nteract@0.0.1 prebuild D:\src\nteract
> rimraf build

> nteract@0.0.1 build D:\src\nteract
> babel src --out-dir build

src\main\index.js -> build\main\index.js
src\main\launch.js -> build\main\launch.js
src\main\menu.js -> build\main\menu.js
src\notebook\actions\index.js -> build\notebook\actions\index.js
src\notebook\agendas\index.js -> build\notebook\agendas\index.js
src\notebook\api\kernel.js -> build\notebook\api\kernel.js
src\notebook\api\messaging\completion.js -> build\notebook\api\messaging\completion.js
src\notebook\api\messaging\index.js -> build\notebook\api\messaging\index.js
src\notebook\api\messaging\inspect.js -> build\notebook\api\messaging\inspect.js
src\notebook\api\messaging\kernel-info.js -> build\notebook\api\messaging\kernel-info.js
src\notebook\api\save.js -> build\notebook\api\save.js
src\notebook\components\cell\cell-creator-buttons.js -> build\notebook\components\cell\cell-creator-buttons.js
src\notebook\components\cell\cell-creator.js -> build\notebook\components\cell\cell-creator.js
src\notebook\components\cell\cell.js -> build\notebook\components\cell\cell.js
src\notebook\components\cell\code-cell.js -> build\notebook\components\cell\code-cell.js
src\notebook\components\cell\draggable-cell.js -> build\notebook\components\cell\draggable-cell.js
src\notebook\components\cell\editor.js -> build\notebook\components\cell\editor.js
src\notebook\components\cell\inputs.js -> build\notebook\components\cell\inputs.js
src\notebook\components\cell\markdown-cell.js -> build\notebook\components\cell\markdown-cell.js
src\notebook\components\cell\pager.js -> build\notebook\components\cell\pager.js
src\notebook\components\cell\toolbar.js -> build\notebook\components\cell\toolbar.js
src\notebook\components\notebook.js -> build\notebook\components\notebook.js
src\notebook\components\util\provider.js -> build\notebook\components\util\provider.js
src\notebook\constants\index.js -> build\notebook\constants\index.js
src\notebook\global-events\index.js -> build\notebook\global-events\index.js
src\notebook\index.js -> build\notebook\index.js
src\notebook\keys\keymap.js -> build\notebook\keys\keymap.js
src\notebook\menu\index.js -> build\notebook\menu\index.js
src\notebook\native-window\index.js -> build\notebook\native-window\index.js
src\notebook\publication\github.js -> build\notebook\publication\github.js
src\notebook\reducers\app.js -> build\notebook\reducers\app.js
src\notebook\reducers\document.js -> build\notebook\reducers\document.js
src\notebook\reducers\index.js -> build\notebook\reducers\index.js
src\notebook\store\index.js -> build\notebook\store\index.js

> nteract@0.0.1 start D:\src\nteract
> electron .
```

Which throw an error:

```
A JavaScript error occurred in the main process

Uncaught Exception:

TypeError: process.env is not a function 
    at userDataDir
(D:\src\nteract\node_modules\kernelspecs\node_module.. .:43) 
    at Object.dataDirs
(D:\src\nteract\node_modules\kernelspecs\node_module...:14) 
    at Object.findAII
(D:\src\nteract\node_modules\kernelspecs\lib\traverse.js: 58:1... 
    at loadFullMenu (D:\src\nteract\build\main\menu.js:272:22) 
    at EventEmitter.<anonymous>
(D:\src\nteract\build\main\index.js:40:26) 
    at emitOne (events.js:95:20) 
    at EventEmitter.emit (events.js: 182:7)
```

**Comment by rgbkrk** [comment] 2016-04-23 23:58
Whoa, you're the first Windows user to try it out! Thank you! We're definitely going to provide Windows support so I'd love to track this down.

It looks like it's the [kernelspecs](https://github.com/nteract/kernelspecs) module that is causing trouble (and it could be down inside `jupyter-paths`). Let's see if we can find a smaller test case.

Try running this in node:

```
require('kernelspecs').findAll().then(console.log)
```

Couple other diagnostics that I'd like to know about:
- Are you using Anaconda's Python distribution?
- How is the Jupyter kernel installed?
- What version of Windows are you on?

**Comment by rgbkrk** [comment] 2016-04-24 00:03
Cool. I just reproduced this on a clean Windows 10 machine.

**Comment by rgbkrk** [comment] 2016-04-24 01:42
Still more to do it looks like, in terms of `sys-prefix-promise`:

```
PS C:\Users\kyle\kernelspecs> node
> require('.')
require('.')
{ findAll: [Function: findAll] }
> require('.').findAll()
Promise { <pending> }
> require('.').findAll().then(x => console.log(x)).catch(err => console.error(err))
Promise { <pending> }
> { [Error: Command failed: python -c 'import sys; print(sys.prefix)'
  File "<string>", line 1
    'import
          ^
SyntaxError: EOL while scanning string literal
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'python -c \'import sys; print(sys.prefix)\'' }

```

**Comment by klonuo** [comment] 2016-04-24 01:49
Hi, thanks for your fast reply
I run Python 3.5 (besides Python 2.7) and use pip, on Windows 10

In the meantime, I upgraded node from 4.x to 5x and npm.
I pulled new changes and installed again.

I got error for keyboard-layout, but as I understand that's osx specific module.

Now when I try to run I get error about electron:

```
...
> nteract@0.0.1 start D:\src\nteract
> electron .

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\src\nteract\node_modules\electron-prebuilt\path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (D:\src\nteract\node_modules\electron-prebuilt\index.js:4:42)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
```

Running simply `electron .` on command line shows blank electron.

---

Ah, I see you found other niceties...

**Comment by rgbkrk** [comment] 2016-04-24 01:54
Since you did a node upgrade, make sure to delete `node_modules` and `npm install` again, as the native libraries need to be built for the new version.

**Comment by klonuo** [comment] 2016-04-24 02:02
I removed whole nteract folder and git cloned it again after node install, if that's what you mean.

PS. I'd like to help, but I just started to learn js which I successfully avoided so far. However I love ipython and jupyter, and that's why I tried to see your project.

**Comment by rgbkrk** [comment] 2016-04-24 02:06
That certainly ensures a clean setup! You're all set there then. I'll be back on later to keep going with my Windows build as well as the fixes that come up. Hopefully you and I will get the Windows setup in excellent shape!

**Comment by klonuo** [comment] 2016-04-24 02:08
Sure :)

**Comment by rgbkrk** [comment] 2016-04-24 03:23
Directly in PowerShell this works with Python:

```
PS C:\Users\kyle\kernelspecs> python -c "import sys; print(sys.prefix)"
C:\Users\kyle\Anaconda2
```

Same thing with singlequotes too.

Time for me to find out why the `sys-prefix-promise` code is not spawning properly on Windows.

**Comment by klonuo** [comment] 2016-04-24 03:41
I cant still get there.
Yesterday installing took quite some time, while today after updating node and npm, this package installs relatively quickly.

Here is verbose installation log, in case of interest: [npm-debug.log (700K)](https://gist.githubusercontent.com/klonuo/f4402f05e825d9658e2e652a45348b79/raw/43b622f82dde559db51c089969df75f6411b6756/npm-debug.log)

**Comment by rgbkrk** [comment] 2016-04-24 04:38
Fixed up sys-prefix-promise https://github.com/rgbkrk/sys-prefix-promise/pull/3 and followed it up by bumping the dependency for `jupyter-paths`. Now this works:

```
PS C:\Users\kyle\jupyter-paths> node
> require('.').dataDirs({withSysPrefix: true}).then(console.log).catch(console.error)
Promise { <pending> }
> [ 'C:\\Users\\kyle\\AppData\\Roaming\\jupyter',
  'C:\\Users\\kyle\\Anaconda2\\share\\jupyter',
  'C:\\ProgramData\\jupyter' ]
```

**Comment by rgbkrk** [comment] 2016-04-24 04:41
Yay, `kernelspecs` is ready to go too!

```
PS C:\Users\kyle\kernelspecs> node
> require('.')
{ findAll: [Function: findAll] }
> require('.').findAll()
Promise { <pending> }
> require('.').findAll().then(console.log).catch(console.error)
Promise { <pending> }
> { python2:
   { name: 'python2',
     files:
      [ 'C:\\Users\\kyle\\AppData\\Roaming\\jupyter\\kernels\\python2\\kernel.json',
        'C:\\Users\\kyle\\AppData\\Roaming\\jupyter\\kernels\\python2\\logo-32x32.png',
        'C:\\Users\\kyle\\AppData\\Roaming\\jupyter\\kernels\\python2\\logo-64x64.png' ],
     resources_dir: 'C:\\Users\\kyle\\AppData\\Roaming\\jupyter\\kernels\\python2',
     spec: { display_name: 'Python 2', language: 'python', argv: [Object] } } }
```

**Comment by rgbkrk** [comment] 2016-04-24 04:44
> I cant still get there.

I'm not there yet either, whittling off little issues here and there. The harder one is going to be ZeroMQ since I have the Visual Studio C++ tools installed directly instead of the old one that node-zmq requires...

**Comment by rgbkrk** [comment] 2016-04-24 04:45
The log helps! I'll be digging in. Thank you @klonuo.

**Comment by rgbkrk** [comment] 2016-04-24 04:46
I've changed the title since the title that was in the issue before has been fixed, yet we're not all the way there for Windows.

**Comment by klonuo** [comment] 2016-04-24 08:01
Yes, zmq is painful to install anywhere. But global npm install goes fine here. I also succeeded with hydrogen on atom previously. And now after updating atom and node, I reinstalled to latest hydrogen. Works very nice, although I use Sublime ;)

In nteract I installed manually electron and zmq, and when I run I get this error:

```
"A dynamic link library (DLL) initialization routine failed.
 \\?\D:\src\nteract\node_modules\zmq\build\Release\zmq.node"
```

which points to `D:\src\nteract\node_modules\bindings\bindings.js:83`.
I added breakpoint, but nothing too obvious for me there. It seems that on line 76 at `require(n)` (n = "D:\src\nteract\node_modules\zmq\build\Release\zmq.node") it fails, although running `require` in zmq like in your examples, it looks fine: [node output](https://gist.github.com/klonuo/cffc52512b2162883519e375cb5b6baf)

**Comment by ankostis** [comment] 2016-08-16 15:16
On Windows, I managed to build everything with the project history a week back, 
AFTER having installed globally `node-gyp`.

I'm not sure what fixed it:
- fetching latest 0.0.5 sources?
- installing `node-gyp` in a separate step?

Anyway, I then had another problem when launching it, I receive a message that the bindings could not be found on the main window:
![image](https://cloud.githubusercontent.com/assets/501585/17585136/5960b1a6-5fba-11e6-9fa5-bc776c064593.png)

I'm copying from the webdev-console the tries directories:

```
Error: Could not locate the bindings file. Tried: 
 D:\Work\nteract.git\node_modules\zmq-prebuilt\build\zmq.node 
 D:\Work\nteract.git\node_modules\zmq-prebuilt\build\Debug\zmq.node 
 D:\Work\nteract.git\node_modules\zmq-prebuilt\build\Release\zmq.node 
 D:\Work\nteract.git\node_modules\zmq-prebuilt\out\Debug\zmq.node 
 D:\Work\nteract.git\node_modules\zmq-prebuilt\Debug\zmq.node 
 D:\Work\nteract.git\node_modules\zmq-prebuilt\out\Release\zmq.node 
 D:\Work\nteract.git\node_modules\zmq-prebuilt\Release\zmq.node 
 D:\Work\nteract.git\node_modules\zmq-prebuilt\build\default\zmq.node 
 D:\Work\nteract.git\node_modules\zmq-prebuilt\compiled\6.1.0\win32\x64\zmq.node 
at bindings (D:\Work\nteract.git\node_modules\bindings\bindings.js:88:9) 
at Object.<anonymous> (D:\Work\nteract.git\node_modules\zmq-prebuilt\lib\index.js:6:30) 
at Module._compile (module.js:541:32) 
at Object.Module._extensions..js (module.js:550:10) 
at Module.load (module.js:456:32) 
at tryModuleLoad (module.js:415:12) 
at Function.Module._load (module.js:407:3) 
at Module.require (module.js:466:17) 
at require (internal/module.js:20:19) 
at Object.<anonymous> 
```

I confirm that the bindings file `zmq.node` exists in:

```
.\node_modules\zmq-prebuilt\build\Release\zmq.no
```

The problem is that with the latest source, I cannot even build it.

Is there some better guide fro Windows?

### Note to GH Admins:

you may create a `Windows` label to tag issues like this.

**Comment by captainsafia** [comment] 2016-08-16 15:48
Hello @ankostis! The error that you are getting is due to the fact that Windows is unsupported at the moment. We are working on creating statically-built bindings for zmq on Windows over at [zmq-prebuilt](https://github.com/nteract/zmq-prebuilt). We currently have OS X support and I'm currently working on Linux support. I'm hoping to tackle Windows next.

If you'd like to help out with the effort, I'd be glad to talk with you through it, otherwise we should have a Windows version by the end of this month.

**Comment by ankostis** [comment] 2016-08-16 16:42
Yes, I would like to help; but unfortunately, since I din't manage to make it work, I'm forced into plan-B, python-tk UI, so my availability would be limite.

**Comment by rgbkrk** [comment] 2016-08-16 16:47
We switched to zmq prebuilt recently to try to get it so people don't have to build it locally, which apparently broke it for your local build (reliant on the original zmq). A next first step on the prebuilt setup is to make it default back to the original build (which is what `prebuild` normally does).

Thank you for taking the time to get it working and to comment here.

**Comment by rgbkrk** [comment] 2016-10-07 03:50
We now have a [shipped release](https://github.com/nteract/nteract/releases) for Windows as well as testing on Windows and a plan for the future with building on Windows. I'll go ahead and close this. Feel free to re-open if the core problem is still there.

**Comment by rgbkrk** [comment] 2016-10-07 03:51
Also, noted about the Windows label. Creating that now.

**Closed as completed by rgbkrk** 2016-10-07 03:50 UTC
Labels: question, courage
