### ISSUE TITLE
customizable keyboard shortcuts

### ISSUE THREAD

**Issue by blas-ko** [nteract/archived-desktop-app#1870] opened 2017-08-29 21:03 UTC
Hello! I'm not sure if this have been addressed before, but as a migrating user to nteract from jupyter notebook as many other users here, there would be really nice if there was a customizable way to set keyboard shortcuts in the app.
Maybe it would be nice to add some default preset of shortcuts too. Something like 
+ nteract (default)
+ jupyter

Anyways, great project; I hope this issue make any sense.

**Comment by blas-ko** [comment] 2017-09-05 14:34
By the way, is there a way to see the default keybindings in the current state? 
Thanks!

**Comment by dhirschfeld** [comment] 2017-09-18 06:06
Potentially dup of #1584.

I'd really like to have this functionality so I'm wondering if this is a new-contributor friendly issue or if it requires a deeper understanding of the `nteract` architecture? The initial goal would be to just add some hard-coded shortcuts and punt on the customization part for now.

**Comment by rgbkrk** [comment] 2017-09-18 16:24
Hard-coded shortcuts are likely `new-contributor-friendly` for implementation, so long as they're key combos (not a command mode). I may (personally) be a bit picky about what combos they are, we do have flexibility though since we control the whole app / window.

**Comment by dhirschfeld** [comment] 2017-09-18 22:57
I'm not advocating for a Command Mode for nteract as I know and understand the reasons why the core devs don't want to go down that route, *however* in the notebook the command mode allows you to perform operations on the cells themselves which can be a huge productivity boost as compared to having to use the mouse.

My suggestion would be to have operations which act on the cells themselves to use the `Ctrl-Shift` modifier. The three most important shortcuts I'd like to add would then be:
 * `Ctrl-Shift-A` - Add cell above
 * `Ctrl-Shift-B` - Add cell below
 * `Ctrl-Shift-D` - Delete cell

You could keep `Ctrl-Shift-N` as an alias for `Ctrl-Shift-B` but I think having the shortcuts mirror those of the notebook gives a huge benefit in terms of muscle memory and makes transitioning between JupyterLab, the classic Notebook and nteract much easier.

Other shortcuts which would be useful:
 * `Ctrl-Shift-Y` - Change cell to code
 * `Ctrl-Shift-M` - Change cell to markdown
 * `Ctrl-Shift-R` - Change cell to raw

Dragging and dropping cells is a nice UI but it would also be good to have keyboard shortcuts to do the same. My suggestion would be that `Ctrl-Shift-{click}` would allow you to select one or multiple cells and then `Ctrl-Shift-C` would copy them, `Ctrl-Shift-X` would cut them and `Ctrl-Shift-V` would paste any copied cells.

My initial goal and highest value-added (for me) would be to just implement A/B/D. Would be interested to hear your thoughts on the above ideas and the concept of using `Ctrl-Shift` to indicate operations *on* cells.

**Comment by rgbkrk** [comment] 2017-09-19 03:50
I think I like those keys! I also _think_ we already have `ctrl-shift-c / x / v` (`cmd-shift-c` on mac) available for copy/cut/paste for cells, but the cell has to be focused. That could be refined.

Would "add cell" default to code or to what your last cell type was?

Since movement between cells can be done with only up/down alone, I'd be tempted to use ctrl-shift-up to create cells (or does that make more sense as "go to the top cell")?

**Comment by dhirschfeld** [comment] 2017-09-19 04:20
I see `Ctrl-Shift-X` will cut a cell - cool! I can't seem to paste cells though with `Ctrl-Shift-V` or even just `Ctrl-V`

> *Would "add cell" default to code or to what your last cell type was?*

I'd just follow what JupyterLab does in this instance to minimize any cognitive dissonance when switching

> *Since movement between cells can be done with only up/down alone, I'd be tempted to use ctrl-shift-up to create cells?*

Similarly, I'd be inclined to not stray too far from the shortcuts already used in the notebook - hence my suggestion of A/B. I could just be particularly bad at context-switching but I do currently find myself constantly polluting my nteract notebooks with random As and Bs! :stuck_out_tongue_winking_eye: 

Assuming you can select multiple cells I would use `Ctrl-Shift-Up` to include the cell above in the current selection if the current selection was above the anchor cell or to remove the last cell from the selection if the selection was below the anchor cell and vice-versa for `Ctrl-Shift-Down`

Since that's probably as clear as mud, here's a gif of the intended behaviour:
![selectcells](https://user-images.githubusercontent.com/881019/30575579-2d784fc6-9d45-11e7-800c-f20bb344e12c.gif)

...i.e. `Ctrl-Shift-Up/Down` should behave similarly to extending a selection of cells in a spreadsheet using `Shift-Up/Down`

`Ctrl-Home` would be a useful shortcut to go to the top of the document.

**Comment by dhirschfeld** [comment] 2017-09-19 04:23
NB: I'm running the latest nteract release on Windows - `0.2.0`

**Comment by blas-ko** [comment] 2017-10-13 20:16
I think @dhirschfeld ideas are great and would make transition from **Jupyter** really smooth! I would love to pull of a PR, but honestly I've got no idea on how to manipulate the code for this... 

It would be awesome if **nteract** could have a list of available shortcuts just as **Jupyter** has (see the image)

![kbsc](https://user-images.githubusercontent.com/8909006/31564697-77c88928-b029-11e7-9040-01ea34c354c6.png)

**Comment by dhirschfeld** [comment] 2017-10-20 00:16
I'll add another - `Ctrl-Shift-Z` undo last cell operation . In particular, undo delete cell :sob:

**Comment by eevleevs** [comment] 2018-10-25 07:42
> I'll add another - `Ctrl-Shift-Z` undo last cell operation . In particular, undo delete cell 😭

`Ctrl-Shift-Z` is usually *redo*. Needs to be something else.

**Comment by stormpython** [comment] 2019-01-23 01:19
Closing in favor of #4101.

**Closed as completed by stormpython** 2019-01-23 01:19 UTC
Labels: keybindings, outdated
