### ISSUE TITLE
Documentation shortcuts a la Jupyter

### ISSUE THREAD

**Issue by j6k4m8** [nteract/archived-desktop-app#1546] opened 2017-03-10 03:18 UTC
The <kbd>Shift</kbd>+<kbd>tab</kbd> shortcut to peek at function signature and documentation is incredibly helpful, and I find myself using Jupyter's web interface instead of nteract whenever I'm working with a library I don't know particularly well. The dropdown suggestions are great, but aren't all the way there yet.

Curious what sort of development overhead you predict this addition would involve. I'd love to get involved in the project, and this might be a good place for me to start out!

**Comment by rgbkrk** [comment] 2017-03-10 18:06
Great!

There's work in progress by @alexandercbooth in #1488. I'd see where you can lend hand in testing that and figure out where Alex is at with it. It looks _really_ close to being ready.

Closing as duplicate of #1254.

**Closed as completed by rgbkrk** 2017-03-10 18:06 UTC
Labels: keybindings
