### ISSUE TITLE
Markdown parsing is not correct when bold and italic text are adjacent to each other

### ISSUE THREAD

**Issue by chenxinyanc** [nteract/archived-desktop-app#4562] opened 2019-09-10 11:06 UTC
**Application or Package Used**
* `@nteract/markdown v4.0.1`

**Describe the bug**
`MarkdownRender` renders the following text
```markdown
**bold***italic*
```
as
> **bold**<wbr />*italic\*

rather than
> **bold***italic*

**To Reproduce**

See https://github.com/chenxinyanc/nteract-test .

**Expected behavior**

**Screenshots**
```tsx
const App: React.FC = () => {
  return (
    <div className="App">
      <header className="App-header">
        <MarkdownRender source="test **test***content*" />
        <MarkdownRender source="test **test** *content*" />
      </header>
    </div>
  );
}
```
renders into
![image](https://user-images.githubusercontent.com/50703224/64608690-d1b50980-d3fd-11e9-8eef-e7f2905276d6.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chromium Edge
- Version 78.0.262.0

**Additional context**

**Comment by captainsafia** [comment] 2019-09-10 20:36
Thanks for opening this issue and taking the time to create a reproduction, @chenxinyanc!

I was able to reproduce the issue on the [demo app for  react-markdown](https://rexxars.github.io/react-markdown/) which is the package that we use to render Markdown in the @nteract/markdown component. 

We might be able to [configure](https://github.com/rexxars/react-markdown#options) react-markdown to render this type of Markdown correctly when there is no whitespace between characters.

Can you open a corresponding issue in the react-markdown repo to see what insights they have on this?

**Comment by captainsafia** [comment] 2019-12-04 19:29
It looks like there hasn't been a response in the issue in `react-markdown`.  I took another look at the configurability options for react-markdown and nothing immediately stands out that would solve this problem.

I'm going to go ahead and close this issue since it is external and relatively low-pri. If you end up finding a solution for this, please do share! Thank you.

**Closed as completed by captainsafia** 2019-12-04 19:29 UTC
Labels: outdated
