### ISSUE TITLE
Can't load any kernel when opening a notebook that has not been created with nteract

### ISSUE THREAD

**Issue by vhoulbreque** [nteract/archived-desktop-app#2235] opened 2017-12-22 14:26 UTC
## Description
When I create a new notebook, I can load any kernel and it works perfectly fine.
But when I open an existing notebook, I cannot load any existing kernel and the code cannot be executed unless this notebook was created using nteract.

### Not working example
1. 'File' -> 'Open' 
2. Choose a notebook that has not been created using nteract
3. 'Language -> Choose a kernel -> Nothing happens (Note the  'Loading... | not connected' at the bottom left)

### Working example
1. 'File' -> 'New' -> Choose a kernel
2. Type some instructions and execute them
3. Save and quit
4. Open the notebook you just saved with nteract
5. Kernel is found and execution works fine

## Versions
Atom     : 1.16.0
Electron: 1.3.13
OS        : Ubuntu 14.04

**Comment by olegantonyan** [comment] 2017-12-23 05:20
Same here, but I even can't execute an example notebook. It says `Python 3 | idle` at the bottom, but can't execute anything.
But it works with a new file, or the file saved with nteract

openSUSE Tumbleweed 64bit, nteract from latest git

**Comment by Madhu94** [comment] 2017-12-29 15:02
@vinzeebreak @olegantonyan I think after the fix in #2256 (it will be in the next release), this won't be an issue

**Comment by olegantonyan** [comment] 2017-12-29 15:25
Confirmed. Latest master works for me
Thank you @Madhu94

**Comment by rgbkrk** [comment] 2018-04-13 17:36
Sounds like it's fixed and certainly shipped since we've made many releases since January.

**Closed as completed by rgbkrk** 2018-04-13 17:36 UTC
Labels: outdated
