### ISSUE TITLE
Example notebook, "Make progress (Bars) with updatable outputs", not working properly

### ISSUE THREAD

**Issue by josujugo** [nteract/archived-desktop-app#4951] opened 2020-02-24 22:59 UTC
Using nteract desktop  v0.22.0: Calm Cajal. Python version 3.7.3

**Describe the bug**

The example notebook "Make progress (Bars) with updatable outputs" does not update properly the output, using display_id='some_destination', update=True).

I have seen similar issues in the past. 

**To Reproduce**

Run the example

**Desktop (please complete the following information):**

- OS:  macOS

**Comment by willingc** [comment] 2020-03-08 16:33
Thanks for the report @josjugo.

Confirming that the example notebook is not performing as expected.

**Comment by captainsafia** [comment] 2020-03-22 18:48
Something is probably up with our handling of updating display outputs. I'll take a look at this for the March release.

**Comment by josujugo** [comment] 2020-03-22 18:53
Great! I'll test the new release as soon as is accesible.

**Comment by captainsafia** [comment] 2020-03-24 00:23
This is fixed now and should be released next week.

**Comment by josujugo** [comment] 2020-03-24 09:04
Hi again:

I have tested in the master branch this issue. Now, if i display the object content (the bar, the text), all the elements with the same id are **correctly** updated. However, if I update the content, this is not shown (as expected), but the content is not changed in the previously shown elements. For instance, the sentence:

h3 = display('no output here, update above', display_id='some_destination', update=True)	

This sentence doesn't change the value of the previouly shown h1 and h2 displays.

I don't know if this is a bug in my local instalation (macos catalina) or is general.

Best regards

**Comment by captainsafia** [comment] 2020-03-25 02:12
@josujugo Thanks for trying this out and following up. I'm unable to reproduce this on my local machine, which is also macOS.

![display-updates](https://user-images.githubusercontent.com/1857993/77494436-f81f1d00-6e02-11ea-8bdb-9dcc63cbdae0.gif)

What version of Jupyter are you on? Also, how did you go about building the master branch bits?

**Comment by josujugo** [comment] 2020-03-25 08:20
Ah, ok! Yes, I have an outdated jupyter versión. I will update it and test again.
Thanks!

**Comment by josujugo** [comment] 2020-03-25 15:40
I have updated jupyter and the result is the same. I run nteract directly from the master version using:

yarn app:dekstop

I have tried to do
yarn install

But I get and error compiling zmq. Basically

configure: error: C compiler cannot create executables

**Comment by captainsafia** [comment] 2020-03-26 02:01
@josujugo These issues tend to happen when certain C-libraries aren't configured properly on the host machine.

Can you try running `yarn clean` to clear out the installed dependencies and packages then re-running `yarn` and `yarn start`?

Alternatively, you can try running the Jupyter extension that runs in the browser alongside the Jupyter server (which does not require any C-libs). You can find the setup instructions for the Jupyter extension [here](https://github.com/nteract/nteract/tree/master/applications/jupyter-extension).

**Comment by josujugo** [comment] 2020-03-26 09:31
I have tried the desktop version without luck (after yarn clean, yarn, yarn start). However, the jupyter version works like a charm

I have updated all the system.

**Comment by captainsafia** [comment] 2020-03-27 00:15
@josujugo Got it! Yeah, setting up the desktop environment can be tricky because of the zeromq dependency.

Thankfully, the code that handles the update_displays is common across both the desktop app and the web app. Did you verify that update displays work in the web app?

**Comment by josujugo** [comment] 2020-03-27 08:25
Yes, the web app is working properly

**Comment by captainsafia** [comment] 2020-03-29 18:01
Got it. I'll go ahead and close this issue. If it works in the web app it should work in the desktop app as well.

**Closed as completed by captainsafia** 2020-03-29 18:01 UTC
Labels: bug
