### ISSUE TITLE
nteract 0.12.2, Anaconda3 on win7. after close continues process in back ground with 50% cpu use!

### ISSUE THREAD

**Issue by jdwolken** [nteract/archived-desktop-app#3604] opened 2018-11-02 23:45 UTC
nteract 0.12.2, Anaconda3 on win7. 
runs correctly after start with double click on ipynb notebook. 
Nice program except for:
The problem starts after closing nteract.
nteract continues to run as a service in the back ground with 50% cpu use!
I have to kill the process with windows taskmanager to get it to stop.

**Comment by Lokdal** [comment] 2018-11-06 14:47
I have the some problem.
Windows 10 x64, nteract 0.12.2, python 3.7.
CPU usage is as expected during use. Only once I close it do I get the ramp up in CPU usage. My usage is about 30% on a 4 cores / 8 threads CPU, suggesting it's using 2 threads.

**Comment by jameskoch** [comment] 2018-11-06 16:39
I can't reproduce this exact behavior in my Windows env, but we've identified some APIs inside the Electron platform which are problematic on Windows. 0.12.3 will mitigate one of these, from #3549. 

Can you try this unreleased 0.12.3 build? https://github.com/nteract/nteract/releases/download/untagged-1ab491dcaaa5045f70a0/nteract-setup-0.12.3.exe

UPD - Ah sorry, I don't think you'll have access to that. Maybe @rgbkrk can grant it somehow, or publish.

**Comment by rgbkrk** [comment] 2018-11-06 16:42
Let me get that wrapped up now and it'll be shipped for the world.

**Comment by jdwolken** [comment] 2018-11-06 17:49
The version of this file is not compatible with the version of windows I am
running (win7, x64)

**Comment by rgbkrk** [comment] 2018-11-06 17:56
https://github.com/nteract/nteract/releases/download/v0.12.3/nteract-setup-0.12.3.exe should be the right one now.

**Comment by jdwolken** [comment] 2018-11-06 18:04
Does not work for my win7, x64 setup

**Comment by jameskoch** [comment] 2018-11-07 19:52
Can you provide more details? This worked fine on my Win7 x64. 

@Lokdal would also love for you to try out this build.

**Comment by jdwolken** [comment] 2018-11-07 23:30
The new version nteract-setup-0.12.3.exe is working fine. It has several
processes running when active as can be seen in the windows task manager.
When quiting nteract all process are killed properly.

In the old version upon exiting the processes (as seen in task manager)
kept active and used up to 50% of CPU time.

Thanks for fixing the problem!



The previous version would

**Closed as completed** 2018-11-08 15:11 UTC
Labels: windows, app:desktop, outdated
