### ISSUE TITLE
Undo the remove operation on nteract cell?

### ISSUE THREAD

**Issue by woraperth** [nteract/archived-desktop-app#3250] opened 2018-08-23 04:34 UTC
Hi,

I love using nteract to analyze the data. The only problem is there seems to be no way to restore the code cell I just deleted. Please kindly let me know if there is a way to do that.

Cheers,
Perth

**Comment by eevleevs** [comment] 2018-10-25 07:36
Same as #1038

**Comment by willingc** [comment] 2018-12-18 04:10
Hi folks. Thanks for the report. I'm closing this as a duplicate of #1038

**Closed as completed by willingc** 2018-12-18 04:10 UTC
Labels: outdated
