### ISSUE TITLE
JS/Node: editing const/let declarations throws SyntaxError

### ISSUE THREAD

**Issue by kredati** [nteract/archived-desktop-app#1864] opened 2017-08-26 23:06 UTC
In the JS/Node REPL, if you declare a variable using `const` or `let` in part of a notebook, run it, and then go back and change the declared values at a later time, the interpreter throws `SyntaxError: Identifier 'foo' has already been declared`.

This is presumably because of how `const` and `let` are different from `var`:

```
var foo // undefined
var foo // undefined
```

```
let foo // undefined
let foo // SyntaxError
```

This seems like undesirable behavior. The workaround is okay (just use `var`!), but for those of us using (& teaching) ES6+, this isn't great.

![nteract error 1](https://user-images.githubusercontent.com/15383681/29745747-99946bb6-8a91-11e7-8cda-836350d9d9f6.png)

![nteract error 2](https://user-images.githubusercontent.com/15383681/29745748-9b227d24-8a91-11e7-9f8f-c2c3b6e2962f.png)

**Comment by rgbkrk** [comment] 2017-09-03 00:42
This uses node/v8 under the hood, so the behavior matches exactly that of node itself (you can see this with the chrome devtools for instance). The workarounds I've been using are to use `var`, like you suggest, on cells I know I'm going to tinker with/reassign and/or restarting the entire kernel (Language -> Restart Kernel). Under the hood we're using [ijavascript](https://github.com/n-riesco/ijavascript), though I don't think it's necessarily behavior we can change.

Bit of a counterpoint -- when teaching `let` and `const`, I'd prefer they match the behavior in all the runtimes available. The only place I'd end up running over them more than once is if they're in a function.

**Comment by therealklanni** [comment] 2017-12-06 21:46
The problem is that in the notebook you haven't _redeclared_ the const/let, the Kernel just _says_ you have. I'm not versed on the internals of how Jupyter kernels work, but it seems like it should start from a clean slate when you run the code block.

**Comment by willingc** [comment] 2018-12-18 10:19
@rgbkrk and others, I'm going to close this as an nteract issue. The behavior of a kernel depends on the implementation of the individual kernel instead of the nteract UI. Please reach out to us on slack if you have additional questions about nteract.  :smile:

**Closed as completed by willingc** 2018-12-18 10:19 UTC
Labels: outdated
