### ISSUE TITLE
dotnet Kernels do not load logos on binder

### ISSUE THREAD

**Issue by colombod** [nteract/archived-desktop-app#4917] opened 2020-02-10 16:46 UTC
**Application or Package Used**
When using nteract in binder with the [dotnet interactive kernels](https://github.com/dotnet/interactive)  the landing page doesn't contain the kernel logos

**Describe the bug**
When I open the binder [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/dotnet/interactive/master?urlpath=nteract) I see all kernel installed but the dotnet interactive kernel are missing the logos while this binder [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/dotnet/interactive/master?urlpath=lab) will respect them

**To Reproduce**

1. Open the binder [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/dotnet/interactive/master?urlpath=nteract)
3. See error as per screenshot

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/375556/74170113-4d70e780-4c24-11ea-892e-d69f82deb791.png)

**Desktop (please complete the following information):**

- OS: Ubuntu bionic
- Browser : Edge Chromium

**Comment by willingc** [comment] 2020-03-08 16:16
Thanks for the report @colombod. 

All, I'm able to reproduce using the first link. Additionally, I am unable to change kernels when running the missing logo example on binder.

Further work on reproducing and identifying the underlying issue is needed.

**Comment by willingc** [comment] 2020-03-08 17:33
Did a bit of sleuthing on this... First, the suffix at the end of the URL `lab` or `nteract` can be interchanged when binder is running.
It appears that JupyterLab is loading a PNG for the logo while nteract is trying to load an SVG for the same kernel. 
<img width="940" alt="Screen Shot 2020-03-08 at 10 31 01 AM" src="https://user-images.githubusercontent.com/2680980/76167999-41dfe600-6128-11ea-97fa-5a8c58cd3930.png">
<img width="1354" alt="Screen Shot 2020-03-08 at 10 27 10 AM" src="https://user-images.githubusercontent.com/2680980/76168004-499f8a80-6128-11ea-9bab-99f846ab4e6b.png">

**Comment by willingc** [comment] 2020-03-08 17:49
I believe that the fix could be made here: https://github.com/nteract/nteract/blob/master/packages/connected-components/src/new-notebook-navigation/logos.tsx

I think the dotnet interactive logos could be added. One concern that I have is that it's not scalable to other kernels beyond those listed - though maybe that's ok.

**Comment by colombod** [comment] 2020-03-08 18:28
> I believe that the fix could be made here: https://github.com/nteract/nteract/blob/master/packages/connected-components/src/new-notebook-navigation/logos.tsx
> 
> I think the dotnet interactive logos could be added. One concern that I have is that it's not scalable to other kernels beyond those listed - though maybe that's ok.

I agree with you, the approach is not scalable. This is something confusing if nteract to has special behaviour for some kernels. Would could be the more general approach here? If nteract requires content from kernel modules then it is a responsibility of kernel authors. But the approach should be general and working for all kernels, not just for few

**Comment by captainsafia** [comment] 2020-03-09 17:22
I did some looking into this earlier.

nteract does extract out the svg image assets as opposed to the png image assets. For the kernels in the logos.tsx files above, it uses those assets. For other kernels, it uses the SVG set in the kernelspec assets. The dotnet kernels are correctly setting the svg image assets.

The issue seems to occur when they are pulled out from the Immutable representation of the kernelspec and mapped to the navigation component for rendering. I wasn't able to track down why this was happening. When I stepped through the debugger, I noticed it would extract the correct SVG for the first kernel then clear out the list in the second loop. I suspect it has something to do with the way we use `reduce` in that code fragment.

In either case, considering the focus on `@nteract/web` and the new UX that removes the UI with the bug, I'm going to mark this as `wont-fix` so we can focus efforts on new UI instead of fixing bugs in the old one.

**Comment by willingc** [comment] 2020-03-16 02:27
@captainsafia @colombod I've gone ahead and labeled this `review-after-nteract:web` work is done. This issue will be part of a group of issues which we will doublecheck are resolved after the new UX. Since the label reflects this next action, I'm going to close this issue.

**Closed as completed by willingc** 2020-03-16 02:27 UTC
Labels: Error UI/UX, outdated, review-after-nteract:web
