### ISSUE TITLE
Mac app tells me it will update but never does

### ISSUE THREAD

**Issue by mbauman** [nteract/archived-desktop-app#4361] opened 2019-04-19 20:58 UTC
**Application or Package Used**
nteract desktop, version 0.12.3

**Describe the bug**
On launch I get a notification there's a new release that's been downloaded and will be installed upon re-launch, but it never happens.  I always get the notification and after successive quit/restarts I always remain on 0.12.3.

**Screenshots**
This notification appears on every launch but the app is never updated.
![Screen Shot 2019-04-19 at 3 54 00 PM](https://user-images.githubusercontent.com/154641/56443815-d0067000-62bb-11e9-9a01-28223ee3f505.png)

**Desktop (please complete the following information):**
- OS: macOS

**Comment by captainsafia** [comment] 2019-04-22 02:32
Hello @mbauman! Thanks for opening this issue. It's a duplicate of https://github.com/nteract/nteract/issues/4329, so I will go ahead and close it.

It seems like this was an isolated problem caused in the last release. Things should be smoothed out in the v.0.14.0 release that will go live tomorrow.

**Closed as completed by captainsafia** 2019-04-22 02:32 UTC
Labels: outdated

**Comment by mbauman** [comment] 2019-04-23 14:41
Thanks!
