### ISSUE TITLE
F# Support

### ISSUE THREAD

**Issue by ShalokShalom** [nteract/archived-desktop-app#4432] opened 2019-06-06 09:48 UTC
Hi :hugs: 

So far as I can see, is F# currently unsupported? How exactly do you port/use kernels?

This project is very interesting, especially in combination with Atom integration.

**Comment by wadethestealth** [comment] 2019-06-06 13:38
Search f# kernel. This is already one out there. Once you install it properly set it up with the hydrogen package if you want atom integration

**Comment by ShalokShalom** [comment] 2019-06-06 15:33
Yes, this is exactly what I am asking: How? Is this any different from setting it up for an own instance of Jupyter? https://github.com/fsprojects/IfSharp#linux-local-installation-and-use

Thanks

**Comment by wadethestealth** [comment] 2019-06-06 15:46
Hydrogen should automatically detect kernels that are available, but kernels also require a grammar for hydrogen, so if the kernel and grammar don't match then you map them to each of in the package settings of hydrogen 

So hopefully it's not any different

**Comment by ShalokShalom** [comment] 2019-06-06 22:08
So I should just add support for my language and should be fine? And why is there a specific step for Scala, C++, Javascript and so on mentioned on the homepage? 

I see a lack of clearity in the documention.

**Comment by rgbkrk** [comment] 2019-06-06 22:22
We wanted to create a place where people could add kernel installation instructions to one page so that people could get started quick. You can add F# to the site too by updating  https://github.com/nteract/nteract.io 😄

**Comment by ShalokShalom** [comment] 2019-06-06 22:29
Well, I have no idea how. Still

**Comment by ShalokShalom** [comment] 2019-06-06 22:34
Just look at your page and put yourself into the position of someone who sees it the very first time. It seems like you have to specifically add support for the languages, no where is mentioned that actually all Jupyter languages should work.

You also see zero mentions that Hydrogen is supposed to automatically detect them.

And finally, I am still not certain how to install such a supported kernel, since it seems unclear what could cause potentially an issue and why some languages could need adjustment.

And which adjustment that would be and why..

**Comment by rgbkrk** [comment] 2019-06-06 22:59
We detect any jupyter kernels installed on disk following the current jupyter spec. I don't know much about the F# kernel, though it does look like it has some special install instructions and possibly some special jupyter instructions. Sorry I can't be of more help there, this seems like uncharted territory at the moment!

**Comment by rgbkrk** [comment] 2019-06-06 23:11
As for other languages, I agree we should have some verbage about how it will work for all jupyter kernels!

**Comment by wadethestealth** [comment] 2019-06-06 23:23
All kernels should follow the same communication scheme as defined by jupyter. We lack documentation because we don't have the knowledge to provide information for every language or kernel. It is also unclear to us which issues can arise because it's all based on the setups of the kernels and what they need. For example some kernels must be started from an active environment others don't. We can't possibly predict your issues, but we encourage you to explore and discover and try it out. If it works then great. If it doesn't then we ask you to provide accurate reproduction steps along with the error, in which we will read and attempt to find out what went wrong

**Comment by wadethestealth** [comment] 2019-06-06 23:24
If you believe something should be documented that isn't, we welcome PRs with good suggestions

**Comment by ShalokShalom** [comment] 2019-06-06 23:40
So I have to essentially install Jupyter in order to use nteract and once I have installed a kernel in nteract, I am ready to use it in Atom via Hydrogen. Sounds improvable

**Comment by ShalokShalom** [comment] 2019-06-06 23:41
I will do this for FSharp/OCaml and also commit documentation.

**Comment by captainsafia** [comment] 2020-01-29 22:22
Closing this as we now have instructions how to install the .NET kernel, which provides support for F# on the nteract.io website.

Thanks @colombod for adding this content!

**Closed as completed by captainsafia** 2020-01-29 22:22 UTC
Labels: outdated
