### ISSUE TITLE
Can nteract support input() function?

### ISSUE THREAD

**Issue by ShixiangWang** [nteract/archived-desktop-app#3621] opened 2018-11-06 13:16 UTC
When I tried using `input()` function by nteract, it always fails.

```python
input()


---------------------------------------------------------------------------
StdinNotImplementedError                  Traceback (most recent call last)
<ipython-input-6-9c8b639daf2f> in <module>
----> 1 input()

/Volumes/Data/miniconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py in raw_input(self, prompt)
    846         if not self._allow_stdin:
    847             raise StdinNotImplementedError(
--> 848                 "raw_input was called, but this frontend does not support input requests."
    849             )
    850         return self._input_request(str(prompt),

StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.
```

nteract is really a good software.

Thanks.

**Comment by willingc** [comment] 2018-12-11 20:17
@ShixiangWang Is this still an issue? If so, please provide a bit more information about your configuration. Thanks.

**Comment by ShixiangWang** [comment] 2018-12-12 02:59
Yes. I just download nteract from https://nteract.io/ and still get this issue.

```

[3]!conda -V
conda 4.5.11

[4]!python -V

Python 3.7.0

[5]!uname
Linux
```

**Comment by rgbkrk** [comment] 2018-12-12 03:00
We don't support stdin on nteract frontends yet. I'll go ahead and close this as a duplicate of #741.

Thanks @ShixiangWang and @willingc

**Closed as completed by rgbkrk** 2018-12-12 03:00 UTC
Labels: outdated, workflow: needs user info
