### ISSUE TITLE
Not signed by its publisher

### ISSUE THREAD

**Issue by 0Isaiah** [nteract/archived-desktop-app#5129] opened 2020-05-27 00:59 UTC
**Application or Package Used**
 nteract-Setup-0.23.3.exe

**Describe the bug**
When downloading in windows 10, using edge, I get this message:
This app might harm your device
Microsoft Defender SmartScreen reported that this app is not commonly downloaded or is not signed by its publisher.

Name: nteract-Setup-0.23.3.exe
Publisher: Unknown.

**Desktop (please complete the following information):**

- Windows 10 ver 1909
- MS Edge Version 83.0.478.37 (Official build) (64-bit)

**Comment by captainsafia** [comment] 2020-05-31 17:50
This is a dupe of #4353 and #4435. We have to get a signing certificate for nteract or explore whether distributing via the Windows store might help alleviate the issues around signing.

If you're interested in helping with this effort, feel free to chime in the referenced threads.

**Closed as completed by captainsafia** 2020-05-31 17:50 UTC
