### ISSUE TITLE
Cannot run jupyter nteract

### ISSUE THREAD

**Issue by shiba24** [nteract/archived-desktop-app#3289] opened 2018-09-05 06:49 UTC
Hi, thank you for your kindness in advance.

I am on MacOS 10.12.6 (Sierra), Python 3.5.5 on anaconda 4.0.nteract-on-jupyter is version 1.9.6.
When trying `jupyter nteract` after `pip install nteract_on_jupyter`, it fails with 

```
Traceback (most recent call last):
  File "/Users/shintaro/.pyenv/versions/anaconda-4.0.0/envs/py3/bin/jupyter-nteract", line 7, in <module>
    from nteract_on_jupyter.nteractapp import main
  File "/Users/shintaro/.pyenv/versions/anaconda-4.0.0/envs/py3/lib/python3.5/site-packages/nteract_on_jupyter/nteractapp.py", line 17
    webpack_hot = {"address": f'http://localhost:{webpack_port}/',
                                                                ^
SyntaxError: invalid syntax
```

How can I fix it?

**Comment by alexandercbooth** [comment] 2018-09-06 13:04
Thank you for trying out nteract, @shiba24! 

It looks like the issue is that you are on Python 3.5 and the current release (nteract_on_jupyter v1.9.6) requires >= Python 3.6 (because of the fstrings).

Fortunately, we recently had a contribution that changes this! 

With the next release of nteract_on_jupyter you will be able to use it with Python 3.5. We should be making this release soon. Until then, if you want to use it with 3.5 you could clone the repo and install it with the [development instructions](https://github.com/nteract/nteract/tree/master/applications/jupyter-extension). 😄

**Comment by shiba24** [comment] 2018-09-07 00:03
Thank you very much, @alexandercbooth ! I got it.

By the way, any there any contribution-welcome issues (tags)? If any, I would like to.

**Comment by alexandercbooth** [comment] 2018-09-07 12:32
That's great. You're very welcome, @shiba24!

Absolutely, we would love to have you contribute!

I'd recommend going through the open [issues](https://github.com/nteract/nteract/issues) to try to find one that you'd like to work on. If you'd like, I can help you pick one out that would be good for a first time contributor 👍.

**Comment by alexandercbooth** [comment] 2018-09-18 02:09
We have now released v1.9.7 of nteract_on_jupyter, which is compatible with Python 3.5, so I think it's OK to close this issue now.

@shiba24, now that we can use Python 3.5, that means our [readme](https://github.com/nteract/nteract/tree/master/applications/jupyter-extension) is out of date. Specifically, we no longer need the part that says `(Python 3.6 or greater)`. Would you like to submit a PR to update this? I am happy to help walk you through the process if you'd like 🙂.

**Comment by shiba24** [comment] 2018-09-19 09:50
Thank you very much, @alexandercbooth !
I will update the library and check whether it works.
Also would love to make a new PR!!

**Comment by shiba24** [comment] 2018-09-20 08:47
I checked it worked on my python3.5 (conda) environment and opened a PR #3345 .

Thank you for your kindness and tolerance ;)

**Closed as completed** 2018-09-20 13:23 UTC
Labels: new-contributor-friendly, outdated
