### ISSUE TITLE
Broken Slack link in docs.nteract.io/

### ISSUE THREAD

**Issue by jruales** [nteract/archived-desktop-app#5295] opened 2020-09-19 04:02 UTC
**Repro**
1. Go to https://docs.nteract.io/
2. Click on [nteract Slack community](https://slack.nteract.io/)
3. 404: NOT_FOUND

**Comment by captainsafia** [comment] 2020-09-19 17:14
Closing as a dupe of https://github.com/nteract/nteract.io/issues/303.

**Closed as completed by captainsafia** 2020-09-19 17:14 UTC
