### ISSUE TITLE
Filename not updating after save

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1277] opened 2016-12-12 03:41 UTC
After saving, the filename in the title bar doesn't update which is a bit disconcerting as you're unsure whether or not it actually did anything.

You can force the title bar to update by e.g. opening and closing the SaveAs dialog.

**Comment by jkornblum** [comment] 2016-12-12 13:15
I also observe this on Windows 7. I have to "redraw" the Electron window (e.g. moving it, or resizing it) and the title bar will update. I believe this is an Electron issue, it's mentioned in this [ticket](https://github.com/electron/electron/issues/1821)

What operating system are you using?

**Comment by dhirschfeld** [comment] 2016-12-12 23:00
Sorry, should have mentioned - also Win7. Happy for this to be closed if
it's an upstream issue...

**Comment by captainsafia** [comment] 2017-01-09 09:59
Hi @jkornblum and @dhirschfeld! Thanks for opening this issue.

Can you confirm whether or not you are using the Windows Basic or Windows classic themes mentioned in the issue that @jkornblum linked to?

**Comment by dhirschfeld** [comment] 2017-01-09 23:49
I don't think I've ever use a Windows "theme" so I'm not sure how I would tell what theme if any I'm using. It's a corporate machine so I guess I'm not running any fancy themes.

It is a Citrix desktop though so it's likely that Citrix is also disabling DWM composition and causing problems for Electron.

**Comment by rgbkrk** [comment] 2017-01-20 18:51
I've been able to reproduce this after having a notebook open for a very long time on a mac that has gone through sleep and awake cycles. My kernel connection has been fine throughout but I can't seem to save and replace the filename:

![screen shot 2017-01-20 at 10 47 05 am](https://cloud.githubusercontent.com/assets/836375/22161157/09d15438-defe-11e6-8b8f-9e9ad453c773.png)

Note: this is current `master`, I'm on OS X El Capitan, and using a Node.js kernel.

Since I know where this is occurring, there are two things we have to address:

* Sometimes electron remote objects disappear and have to be recreated. I don't actually know _how_ to deal with this so at the very least a try-catch around the section seems good.
* The entire observable that's handling updates here needs to retry (more like rewire) the originating observable on failure, making sure to catch failures (see #1177)

**Comment by lgeiger** [comment] 2017-01-20 20:28
For reference: https://github.com/electron/electron/issues/8205

**Comment by rgbkrk** [comment] 2017-02-07 01:28
Oh hey, I know how to fix this a bit better now than our current try catch. At any rate, this is "closed" in the sense that we've mitigated it. Need to fix (or document) better how to handle situations like this up in Electron.

**Closed as completed by rgbkrk** 2017-02-07 01:28 UTC
