### ISSUE TITLE
The nteract app hangs on opening in Windows 10

### ISSUE THREAD

**Issue by Mohapatra-Hemanta** [nteract/archived-desktop-app#5208] opened 2020-07-16 15:30 UTC
**nteract app is not opening in Windows 10. This is first time I want to use it and want to use it for Julia. I also have Python installed on my laptop. I tried to install nteract 0.24.0-win multiple times, but same issue. It stops after flashing of the nteract logo.**

**Comment by captainsafia** [comment] 2020-07-17 01:59
Closing as a dupe of #5190.

**Closed as completed** 2020-07-17 02:01 UTC

**Comment by Mohapatra-Hemanta** [comment] 2020-07-19 18:15
I have already checked the inputs in the thread #5190. Tried all possible options. Ran troubleshooter in windows. But still nteract refuses to progress beyond the flashing logo. Is there a 0.23.3 version available anywhere to to try out ?
