### ISSUE TITLE
Dark mode not 'remembered'

### ISSUE THREAD

**Issue by samialsindi** [nteract/archived-desktop-app#5163] opened 2020-06-16 11:16 UTC
**Application or Package Used**
nteract desktop

**Describe the bug**
In previous versions of nteract, if you changed the preference to Dark theme it persisted upon shutdown and reopening of new windows. Recently, however, it always defaults to Light theme.

**To Reproduce**

1. Set theme to Dark.
2. Close
3. Reopen, it opens in Light theme instead of Dark.

**Expected behavior**
It should remember that Dark was chosen and preferred

**Desktop (please complete the following information):**

- OS: the latest versions of nteract desktop on both MacOSX Catalina and Windows 10 (all latest updates)

**Comment by captainsafia** [comment] 2020-06-19 04:27
Thanks for reporting this issue, @samialsindi!

This was a regression that was introduced in the May release. We've already fixed the bug and the bug fix will ship in the June release!

**Comment by captainsafia** [comment] 2020-06-20 23:54
Closing as duplicate of #5134.

**Closed as completed by captainsafia** 2020-06-20 23:54 UTC
