### ISSUE TITLE
Feature Request: support existing kernels

### ISSUE THREAD

**Issue by pylang** [nteract/archived-desktop-app#1249] opened 2016-11-29 22:10 UTC
nteract is beautiful and zen.

Although I have ipykernel installed on several conda envs, I still have to install a kernel manually.  I believe they install for notebooks automatically through `nb_kernels`.   I'm requesting integration of existing kernelspecs from conda, as I don't know what how this manual installation with affect my prior setup.

**Comment by rgbkrk** [comment] 2016-11-29 23:36
Thank you!

Part of this was done in https://github.com/nteract/nteract/blob/master/src/main/kernels.js, we need more adaptation to finish this off. I'll register this mentally as another vote to finish off #357. I know the next steps to take, I haven't had time to do this yet.

@lgeiger -- this relates to how we should be able to take any kernelspec in our current setup to do a run (rather than relying on name alone). We run into an issue when trying to detect the kernel from the notebook vs. a new notebook.

**Comment by rgbkrk** [comment] 2017-02-07 02:27
Closing as duplicate of #357. #1384 took us partway, I would need more time to finish that. Alas, I must admit I don't have time to fully finish that and need someone else to dive in.

**Closed as completed by rgbkrk** 2017-02-07 02:27 UTC
Labels: question, feature: epics
