### ISSUE TITLE
`save` deferral to `saveAs` not working

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#783] opened 2016-09-17 18:53 UTC
This seems to be an issue with the new launch filename mechanics:

![screen shot 2016-09-17 at 11 53 25 am](https://cloud.githubusercontent.com/assets/836375/18610297/5b3e7e38-7ccd-11e6-818f-43fcb2c69806.png)

Reproduction steps:
- Open a new notebook (npm run start in dev for example)
  command-s (to save)
- Error notification pops up

**Comment by captainsafia** [comment] 2016-09-17 18:55
I think this one is one me. Can you reproduce this consistently on Save As?

I encountered this when updating the dialog menus to show the home directory on start. It's complaining because it cannot find `app` from Electron in this case. I wasn't able to reproduce consistently so I figured it was just some voodoo.

**Comment by rgbkrk** [comment] 2016-09-17 18:57
Reproduction steps:
- Open a new notebook (`npm run start` in dev for example)
- command-s (to save)
- Error notification pops up

Note that `saveAs` totally works fine. It's the "whoa we can't save, let's saveas case", which is triggered by save.

**Comment by captainsafia** [comment] 2016-09-17 19:05
Another curious thing — this only happens when Save As is done via a keyboard shortcut, saving through the application menu works fine.

**Comment by captainsafia** [comment] 2016-09-17 19:10
Ah! Got a fix for this. PR inbound.

**Closed as completed** 2016-09-17 19:21 UTC
