### ISSUE TITLE
New versions of nteract_on_jupyter remove bookstore and papermill functionality

### ISSUE THREAD

**Issue by groodt** [nteract/archived-desktop-app#5090] opened 2020-05-09 11:10 UTC
**Application or Package Used**
nteract_on_jupyter

**Describe the bug**
Attempting to integrate nteract_on_jupyter, bookstore and papermill projects appears to be broken beyond version `2.1.3`.

**To Reproduce**

I install `nteract_on_jupyter:2.1.3` as follows:

```
python3 -m pip install nteract_on_jupyter papermill bookstore
jupyter serverextension enable bookstore
jupyter serverextension enable nteract_on_jupyter
jupyter nteract --ip=0.0.0.0
```

This results in a functional nteract_on_jupyter environment, apart from a `bookstore` publishing bug: https://github.com/nteract/nteract/pull/4738)

It results in a UI with bookstore and papermill "parameters" feature. (See Screenshots)

However to get around the bug, attempting to install version `nteract_on_jupyter2.9.1` (appears to be latest release on GitHub) results in an environment with `bookstore` and `papermill` features removed / disabled even though they are installed.

```
NOJ_VERSION=2.9.1
wget https://github.com/nteract/nteract/archive/nteract-on-jupyter@$NOJ_VERSION.tar.gz
tar -xzvf nteract-on-jupyter@$NOJ_VERSION.tar.gz
cd nteract-nteract-on-jupyter-$NOJ_VERSION
yarn install

cd applications/jupyter-extension/nteract_on_jupyter
NODE_OPTIONS="--max-old-space-size=4096" NODE_ENV=production yarn exec webpack

cd ..
python3 -m pip install -e .

python3 -m pip install papermill bookstore
jupyter serverextension enable bookstore
jupyter serverextension enable nteract_on_jupyter
jupyter nteract --ip=0.0.0.0
```

**Expected behavior**
Version `2.9.1` should have bookstore publishing and papermill "parameters" working.

**Screenshots**
2.1.3 have bookstore publishing and papermill "parameters" feature.
<img width="489" alt="Screen Shot 2020-05-09 at 8 37 38 pm" src="https://user-images.githubusercontent.com/343415/81471693-3b5c1080-9236-11ea-8c17-39e4921f009b.png">

2.9.1 has no bookstore publishing or papermill "parameters" feature.

<img width="1670" alt="Screen Shot 2020-05-09 at 9 01 52 pm" src="https://user-images.githubusercontent.com/343415/81471969-5f205600-9238-11ea-8ba8-2340d4d240f9.png">

**Comment by captainsafia** [comment] 2020-05-12 03:15
Thanks for reporting this issue!

With regard to the lack of papermill features in nteract_on_jupyter, there isn't anything interesting that the nteract Jupyter extension or desktop app due besides providing the "Toggle Parmater Cell" option. We anticipate that most people are going to be using papermill via the CLI.

The fact that the "Publish" option doesn't appear in the menu is caused by a bug in the way the extension reads the config. I've submitted a fix for this issue in https://github.com/nteract/nteract/issues/5090.

**Comment by groodt** [comment] 2020-05-12 04:13
> The fact that the "Publish" option doesn't appear in the menu is caused by a bug in the way the extension reads the config. I've submitted a fix for this issue in #5090.

Awesome! Thanks for fixing!

> With regard to the lack of papermill features in nteract_on_jupyter, there isn't anything interesting that the nteract Jupyter extension or desktop app due besides providing the "Toggle Parmater Cell" option. We anticipate that most people are going to be using papermill via the CLI.

This may be true, but then if the "Toggle parameter cell" functionality is there, it should surely display visually in the UI. It is important with papermill to set tags on a cell that indicates "parameters". If the nteract UI doesn't visually display this, then it's difficult to know if a cell with "parameters" has been setup. It's also confusing if the toggle exists, but doesn't toggle anything. If nteract isn't going to support papermill (I would be disappointed), then it would make more sense to remove the toggle entirely and make it clear that users need to set papermill tags via the classic jupyter UI.

**Comment by captainsafia** [comment] 2020-05-12 18:48
At the moment, the toggle does change the cell to a parameterized cell but notably doesn't provide a UI for editing the tags.

This is probably something that we will be able to address after the UI refresh done. We're doing some work to ship a new UX in nteract apps that will change a lot of the look and feel so things like this will have to be revisited when that work wraps up (sometime toward the end of this month/early next).

**Comment by captainsafia** [comment] 2020-05-12 18:50
Closing this in favor of https://github.com/nteract/nteract/issues/5100 which defines the action we can take to resolve this.

**Closed as completed by captainsafia** 2020-05-12 18:50 UTC

**Comment by groodt** [comment] 2020-05-12 22:44
Thanks! Yes, I'd say it's a fairly big UX bug to address. A toggle that silently operates without visually representing a state change is a terrible UX.
