### ISSUE TITLE
Docstring doesn't clear on Clear Cell Output

### ISSUE THREAD

**Issue by nickteff** [nteract/archived-desktop-app#2521] opened 2018-02-12 17:56 UTC
Using v.0.7.1 on Windows 10.  

Attempted to clear a docstring output after doing something like within a cell

```
pandas.DataFrame?
```
Tried clearing the output from the tools in the cell and the toolbar with no luck.

**Comment by rgbkrk** [comment] 2018-02-12 18:11
Thanks for reporting this, which is a duplicate of https://github.com/nteract/nteract/issues/2458 (though hard to tell they're the same issue).

We store those messages separate from the outputs (structure wise), yet they look like outputs to the user. I'm going to switch them to become an actual output so they're clearable and end up in the document if saved (which would also match the actual input, so I think it's a good fit).

**Closed as completed** 2018-02-14 19:25 UTC
