### ISSUE TITLE
Data Explorer: Scatter plots fail to execute

### ISSUE THREAD

**Issue by e184633** [nteract/archived-desktop-app#3272] opened 2018-08-30 09:48 UTC
It  crashes with the following output when I try to use scatterplot: 

 ```
Error: TypeError: r.split is not a function
stack trace


    in t
    in g
    in t
    in Unknown
    in g
    in t
    in g
    in svg
    in div
    in Unknown
    in t
    in div
    in Unknown
    in div
    in Unknown
    in t
    in XYFrame
    in div
    in ResponsiveXYFrame
    in div
    in div
    in div
    in div
    in t
    in t
    in t
    in div
    in t
    in div
    in Unknown
    in div
    in t
    in t
    in Connect(t)
    in div
    in t
    in DropTarget(t)
    in DragSource(DropTarget(t))
    in div
    in div
    in o
    in DragDropContext(o)
    in Connect(DragDropContext(o))
    in t
    in t
    in Connect(t)
    in t
    in Connect(t)
    in t
    in t
    in o
```
Rerunning again allows using other automatically generated plots, but not scatter plots.

**Comment by emeeks** [comment] 2018-09-10 16:29
What dataset are you plotting?

**Comment by emeeks** [comment] 2018-09-13 00:39
@e184633 If you get a chance to post a dataset so I can reproduce this (or point me at a notebook) that would be great, I can't find anything perusing the code that is an obvious suspect.

**Comment by e184633** [comment] 2018-09-21 09:49
> What dataset are you plotting?

Hi @emeeks , it was a proprietary dataset, but I can try tonight to see if it will work on a different dataset, or just take out the column values and post it. I might be asking for too much, but I think the default behaviour needs to be a little different than crashing even if scatter plot is not what you would use for the variables in question, because in data exploratory phase, after playing around and finding interesting interactions between several features in other subplots, it crashed when you click on the wrong button.

**Comment by emeeks** [comment] 2018-10-09 15:33
@e184633 I agree that this shouldn't happen, just let me know how to reproduce it and I'll make sure it's fixed.

**Comment by emeeks** [comment] 2019-04-27 03:50
Going to close this due to lack of reproducibility and age

**Closed as completed by emeeks** 2019-04-27 03:50 UTC
Labels: outdated, data-explorer
