### ISSUE TITLE
drag-and-drop from nteract to macOS Keynote no longer works

### ISSUE THREAD

**Issue by slink** [nteract/archived-desktop-app#4889] opened 2020-01-29 18:21 UTC
**Application or Package Used**
This affects nteract desktop

**Describe the bug**
In the past my workflow involved generating matplotlib / seaborn plots in nteract ipynb files and then dragging-and-dropping them directly into macOS Keynote. This functionality no longer works and all I see is a large text blob in the place of the image. 

**To Reproduce**
1. open an ipynb file in nteract 0.21.0
2. generate a matplotlib figure inline
3. try to drag-and-drop the image into keynote
4. See text blob in keynote instead of image

note, if you drag the image to the desktop, you still get a png as expected (and from the desktop you can still drag it into Keynote). Just the direct drag-and-drop from nteract to Keynote doesn't work anymore. 

**Expected behavior**
I expect the image to drag-and-drop from nteract to keynote as it has in the past. 

**Desktop (please complete the following information):**

- OS: macOS 10.15.1
- macOS Keynote 9.2.1
- nteract 0.21.0

**Comment by captainsafia** [comment] 2020-01-30 19:26
Hello @slink! Thanks for opening this issue. I can reproduce this as well, although I'm not aware of any changes that would've caused this off-hand.

Have the OS and Keynote versions changed between when this was working and now?

**Comment by slink** [comment] 2020-01-30 19:39
Hi @captainsafia, glad it's not just me! As far as I recall the only thing that changed in my setup is my nteract version. I believe I upgraded from 0.15.0 to 0.21.0 and this functionality no longer worked. Not sure where the bug is though.

**Comment by slink** [comment] 2020-02-24 22:45
Just an update that this issue still persists in nteract 0.22.0. I have updated my MacOS in the interim, but the version of Keynote does not appear to have changed. 

-MacOS: 10.15.3
-Keynote: 9.2.1

**Comment by willingc** [comment] 2020-03-08 15:52
Thanks for the update @slink.

**Comment by willingc** [comment] 2020-04-29 15:04
I'm working on MacOS 10.15.4 and Keynote 10.0 (6748).

I was able to reproduce the problem as described. When drag and drop to the desktop, the file is saved as `download.png`. When drag and drop to Keynote, it renders as text (not an image). 

<img width="1115" alt="Screen Shot 2020-04-29 at 7 47 22 AM" src="https://user-images.githubusercontent.com/2680980/80610822-ac0d5c80-89ee-11ea-80a1-3b4ae065c36f.png">

Doing a select all on the text and dropping to the desktop, I see the following:

<img width="873" alt="Screen Shot 2020-04-29 at 7 48 56 AM" src="https://user-images.githubusercontent.com/2680980/80610923-cc3d1b80-89ee-11ea-98b9-35b1b03bb871.png">

What is somewhat odd is that the drag and drop to Keynote and then desktop, the information is set as `data:image/jpeg`. While the direct drag and drop to desktop is PNG.
<img width="260" alt="Screen Shot 2020-04-29 at 7 58 03 AM" src="https://user-images.githubusercontent.com/2680980/80611450-77e66b80-89ef-11ea-991b-0029c2c5fc11.png">

I see the same behavior if I try to drag and drop into a Ulysses markdown app.

**Comment by willingc** [comment] 2020-04-29 15:15
<img width="1156" alt="Screen Shot 2020-04-29 at 8 15 09 AM" src="https://user-images.githubusercontent.com/2680980/80613025-9483a300-89f1-11ea-8f61-2df92ba6e11f.png">

**Comment by captainsafia** [comment] 2020-04-30 23:20
Thanks for sharing the additional examples.

My only immediate intuition is that there might be a regression in the version of Electron that is causing this behavior to stop working.

I bring this up because we don't implement any logic explicitly to support drag-and-dropping images across applications. I've revived #4907 to see if getting on the latest Electron will fix this.

**Comment by willingc** [comment] 2020-05-06 13:56
This is an example of others having a similar issue with Keynote: https://support.google.com/chrome/thread/3461951?hl=en

**Comment by willingc** [comment] 2020-05-06 14:08
Copy and paste of the image does work.

<img width="555" alt="Screen Shot 2020-05-06 at 7 07 37 AM" src="https://user-images.githubusercontent.com/2680980/81187065-690c3580-8f68-11ea-951d-ecd1087e9655.png">

**Comment by willingc** [comment] 2020-05-06 14:34
Drag and drop does work to Keynote if dragged and dropped into the image gallery in the sidebar. You can drag and drop into the **images** section:

<img width="1099" alt="Screen Shot 2020-05-06 at 7 30 39 AM" src="https://user-images.githubusercontent.com/2680980/81189781-d4a3d200-8f6b-11ea-8bf1-0ddff44fef99.png">

**Comment by captainsafia** [comment] 2020-05-07 04:54
Thanks for digging into this, @willingc.

I'm going to close this out since it looks like Keynote/macOS might've changed its functionality here. Perhaos disabling drag-n-drop from other apps to the content window on Keynote...

**Closed as completed by captainsafia** 2020-05-07 04:54 UTC
Labels: Error UI/UX, workflow: needs upstream fix

**Comment by slink** [comment] 2020-05-07 14:51
Hi @captainsafia not that I know enough about the underling drag-and-drop mechanism to dig into this, but given that I (and others) saw this across multiple versions of MacOS / Keynote, where the only thing changing was nteract, leads me to suspect that Keynote is not the culprit. 

The fact that there is also an issue with Chrome may in fact imply some other underlying mechanism or shared piece of code given that nteract is an Electron app and thus relies on Chromium.

**Comment by willingc** [comment] 2020-05-07 18:43
@slink We discussed on the weekly call that it could be a version of Electron that may be a cause. Keep an eye on work that will be done in the future to upgrade Electron.

**Comment by captainsafia** [comment] 2020-05-12 01:55
It looks like updating to the latest version of Electron doesn't do anything to solve this issue so there is something funkier going on here.

This is still a bug in the latest version of Chrome ([ref](https://support.google.com/chrome/thread/3461951?hl=en)) so that's likely why upgrading Electron didn't do anything.

For now, we'll have to recommend that folks use copy-paste or drag to the image manager in Keynote.
