### ISSUE TITLE
nteract does not work from conda environment (anymore)

### ISSUE THREAD

**Issue by h-vetinari** [nteract/archived-desktop-app#4720] opened 2019-11-21 15:36 UTC
**Application or Package Used**
nteract desktop (on windows)

**Describe the bug**
It used to be possible (and is still documented as such) to do
```
conda activate myenv
python -m ipykernel install --user --name myenv --display-name "Python (myenv)"
```
from a conda environment, and then use that from within nteract.

**To Reproduce**

1. Download nteract 0.15
1. Create conda environment and install numpy (making sure that the conda `base` environment does not contain numpy, such as after a fresh install)
1. Register the kernel
1. Start nteract and select the kernel
1. Import numpy
1. See DLL-error (cf. #1517)

**Expected behavior**
Numpy import succeeds

**Desktop (please complete the following information):**

- OS: Windows 10 1903

**Additional context**
The bug happens likely exclusively due to wrongly setting up the environment variables, effectively breaking all interaction with conda environments. This is IMHO a massive regression, because it makes nteract completely unusable with on windows in one of the most common workflows. I'm surprised that this is apparently a low priority (cf. #3862 that's recently been closed as stale after about a year).

In particular: within a normal REPL, the path correctly points to the environment
```
> conda activate myenv
> python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print("\n".join(sys.path))

C:\ProgramData\Miniconda3\envs\myenv\python37.zip
C:\ProgramData\Miniconda3\envs\myenv\DLLs
C:\ProgramData\Miniconda3\envs\myenv\lib
C:\ProgramData\Miniconda3\envs\myenv
C:\ProgramData\Miniconda3\envs\myenv\lib\site-packages
C:\ProgramData\Miniconda3\envs\myenv\lib\site-packages\win32
C:\ProgramData\Miniconda3\envs\myenv\lib\site-packages\win32\lib
C:\ProgramData\Miniconda3\envs\myenv\lib\site-packages\Pythonwin
```

whereas within nteract, this does not point to the environment (which is why it won't find the correct DLLs):
```
import sys
sys.path
['<folder of the notebook>',
 'C:\\ProgramData\\Miniconda3\\python37.zip',
 'C:\\ProgramData\\Miniconda3\\DLLs',
 'C:\\ProgramData\\Miniconda3\\lib',
 'C:\\ProgramData\\Miniconda3',
 '',
 'C:\\ProgramData\\Miniconda3\\lib\\site-packages',
 'C:\\ProgramData\\Miniconda3\\lib\\site-packages\\win32',
 'C:\\ProgramData\\Miniconda3\\lib\\site-packages\\win32\\lib',
 'C:\\ProgramData\\Miniconda3\\lib\\site-packages\\Pythonwin',
 'C:\\ProgramData\\Miniconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\<username>\\.ipython']
```

**Comment by captainsafia** [comment] 2019-11-27 20:15
There are some workarounds for this problem [in this issue](https://github.com/nteract/nteract/issues/3670). Let me know if any of those work for you.

I'll close this issue since the one linked above is more authoritative and provides more context.

The priority of the issue is recognized but as this is an open-source project, we can't get around to fixing everything. If you have the expertise and interest to help resolve this, a PR is more than welcome.

**Closed as completed by captainsafia** 2019-11-27 20:15 UTC
Labels: outdated
