### ISSUE TITLE
input() and getpass.getpass() causes error

### ISSUE THREAD

**Issue by pcepulionis** [nteract/archived-desktop-app#3255] opened 2018-08-24 10:35 UTC
Hydrogen and Jupyter supports both inputs (input() and getpass.getpass() ), but nteract causes error.

Code:
```
import getpass
password = getpass.getpass()
```
Causes:

```
---------------------------------------------------------------------------
StdinNotImplementedError                  Traceback (most recent call last)
<ipython-input-16-4f314039529d> in <module>()
      1 import getpass
----> 2 password = getpass.getpass()

~\Anaconda3\lib\site-packages\ipykernel\kernelbase.py in getpass(self, prompt, stream)
    676         if not self._allow_stdin:
    677             raise StdinNotImplementedError(
--> 678                 "getpass was called, but this frontend does not support input requests."
    679             )
    680         if stream is not None:

StdinNotImplementedError: getpass was called, but this frontend does not support input requests.
```

**Comment by willingc** [comment] 2018-12-18 17:21
Thanks for the report @pcepulionis.

I've reproduced this issue for nteract Desktop.

**Comment by captainsafia** [comment] 2019-04-20 02:50
Closing this as it is a duplicate of https://github.com/nteract/nteract/issues/741.

nteract currently doesn't support `input_request` messages. I've started a branch with updates to resolve this and will hopefully have something in soon. In the meantime, we can track this in the master issue.

**Closed as completed by captainsafia** 2019-04-20 02:50 UTC
Labels: bug: ui/ux, stdin, outdated
