### ISSUE TITLE
Toggle Output Visibility not working in desktop

### ISSUE THREAD

**Issue by MSeal** [nteract/archived-desktop-app#5140] opened 2020-06-03 20:55 UTC
**Application or Package Used**
State which application or package this affects. For example: nteract desktop, nteract web, nteract on jupyter, etc.

nteract desktop

**Describe the bug**

Cell output toggle doesn't do anything in desktop app.

**To Reproduce**

1. Open a python3 notebooks
2. Add 
```
%pip install pandas vega_datasets
```
to the first cell and run it
3. Add
```
print("Hello World")
```
and run in the next cell
4. Click on cell options on the right and select Toggle Output Visibility.
5. See that nothing changes.

**Expected behavior**

The cell output should be suppressed visibly.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser Electron
- Version 0.23.3

**Additional context**

**Comment by captainsafia** [comment] 2020-06-03 22:06
Closing as a dupe of #5135.

**Closed as completed by captainsafia** 2020-06-03 22:06 UTC
