### ISSUE TITLE
[Feature Request] Search interpreters instead of kernels

### ISSUE THREAD

**Issue by aitikgupta** [nteract/archived-desktop-app#5345] opened 2020-11-05 08:51 UTC
I've been reading around some issues regarding kernel discovery, and I have a few points:
Right now nteract discovers all jupyter kernels through: `python3 -m jupyter kernelspec list --json`, [ref](https://github.com/nteract/nteract/blob/e0a171427916ceda6b880c420255b184d710503b/packages/fs-kernels/src/kernelspecs.ts#L68).
- Instead of searching for all jupyter kernels, what if nteract searches all the interpreters [This is done in Visual Studio Code Python extension]:
How would it help? If an interpreter does not have a kernel, nteract could raise a popup asking user whether to install the kernel for that interpreter, something like this [This is from VSCode extension again]:
![Screenshot from 2020-11-05 14-00-26 (1)](https://user-images.githubusercontent.com/43996118/98217043-ea706f00-1f6f-11eb-898f-2da2b6466124.png)

A lot of Anaconda related issues could be fixed through this (I think) since _kernels won't be found in some envs, but all envs can be found, regardless of whether having a kernel installed._ We can install kernels in interpreters, but not vice versa.

I think this is somewhat partially related to [one of GSoC ideas](https://github.com/nteract/nteract/wiki/GSoC-2020-Ideas#2-add-support-for-automatic-kernel-discovery-and-installation).

I'm a newbie here, so not sure if what I'm thinking is fully supported by the internal working of nteract, but it's worth a thought. :)

**Comment by captainsafia** [comment] 2020-11-05 22:39
Thanks for opening this issue!

Yep, this is dupe of https://github.com/nteract/nteract/issues/1227.

The feature is definitely supported. Just a matter of carving out the time for implementation.

I'll close this issue in favor of the earlier one. Feel free to transfer your comment over there so we can consolidate the conversation.

**Closed as completed by captainsafia** 2020-11-05 22:39 UTC
