### ISSUE TITLE
Output hyperlink is wrongly made cross lines

### ISSUE THREAD

**Issue by JulianChu1** [nteract/archived-desktop-app#4745] opened 2019-12-06 01:14 UTC
"@nteract/outputs": "2.3.4",
Run a cell like below and the hyperlink is made wrongly

import sys

sys.stdout.write("RunId: 123\n")
sys.stdout.write("Web View: https://ml.azure.com\n")
sys.stdout.write("\n")
sys.stdout.write("Streaming\n")

Result

<a href="https://ml.azure.com

Streaming
" target="_blank">https://ml.azure.com

Streaming
</a>

**Comment by CrystallineCat** [comment] 2019-12-07 13:00
I can't reproduce this on `@nteract/outputs@2.6.0` (current master), using the desktop app.

**Comment by captainsafia** [comment] 2019-12-09 02:39
Same @CrystallineCat!

I reached to to Julian via corporate chat and we confirmed that this issue is indeed resolved in 2.6.0.

If anyone is running into this, make sure you are on at least that version of the outputs package.

I'll go ahead and close this issue.

**Closed as completed by captainsafia** 2019-12-09 02:39 UTC
Labels: bug, outdated, pkg:outputs
