### ISSUE TITLE
Notebook react Component!?

### ISSUE THREAD

**Issue by argenisleon** [nteract/archived-desktop-app#536] opened 2016-06-25 01:00 UTC
Hi,

Is there an easy way to use only the notebook ui in another app?.

**Comment by rgbkrk** [comment] 2016-06-28 20:46
Not quite yet, though I'm planning to work on that myself. We'll likely export more components from this repository (or bring them out) so you can put together what you want.

If you're open to exploring it, I'd love to work together.

**Comment by rgbkrk** [comment] 2016-09-14 23:14
Closing as duplicate of #301.

**Closed as completed by rgbkrk** 2016-09-14 23:14 UTC

**Comment by rgbkrk** [comment] 2018-04-04 01:05
Just an update -- there is now a web version of nteract that runs on top of the jupyter server. You can [try it out on binder!](https://mybinder.org/v2/gh/nteract/vdom/master?urlpath=nteract/edit/example-notebooks)

The jupyter extension is called `nteract_on_jupyter` on PyPI and there are install instructions here: https://github.com/nteract/nteract/tree/master/applications/jupyter-extension

Beyond that, there are related packages for building your own using `@nteract/core`. I don't think the API is stable yet, so you'd have to build along with us.
