### ISSUE TITLE
Lag when saving large notebooks in desktop app

### ISSUE THREAD

**Issue by affans** [nteract/archived-desktop-app#3994] opened 2019-01-07 23:35 UTC
I don't know what information to provide, except I am using `Julia 1.0.0` with the latest version of `IJulia` and fresh install of nteract. I am on 
``` 
OS: macOS (x86_64-apple-darwin14.5.0)
CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
``` 
anything else I can provide to help?

~~Edit: It only hangs if there is a `DataFrame.jl` table on the display. If I clear all output cells, it dosn't hang and the file saves.~~

While I crossed out the above, with a datatable on display it takes a really long time to save. Which implies that once my entire notebook is run with multiple plots and datatables, that it's just taking a really long time to save.

**Comment by willingc** [comment] 2019-01-16 16:51
Thanks @affans for the report. Just to clarify the problem...when running Julia with datatable displays, nteract takes a long time to save notebook file. Is that correct?

**Comment by affans** [comment] 2019-01-17 19:45
@willingc 
Yes, this is reproducible by: 

1) Download the `symp.dat` file from my repository at https://github.com/affans/influenza. This file is a 200 x 500 tab-delimited integer Data. 

2) Open Interact, load relevant Julia libraries in a cell, mainly 
```
using CSV
using DataFrames
```
3) In the next cell, load up this file (making sure to `cd` into the right folder or provide an absolute path)
```
headers = ["sim$i" for i = 1:500]
dt = CSV.File("symp.dat", header=headers, delim='\t') |> DataFrame
```
This will show the dataframe `dt` on the display. 

4) Save the notebook. Takes about 10 - 20 seconds on my machine - during which the entire software is unresponsive. 
5) (optional) Move to the next cell, write something, save again... 

Information:
```
Nteract version: 0.12.3
---- 
julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
```

**Comment by willingc** [comment] 2019-01-17 22:59
Thanks @affans for the detailed reproducibility info. It helped a bunch.

I am definitely seeing a temporary freeze in nteract while the file is being saved. It happened on both the process above and adding another optional cell and saving again.

```
nteract Version 0.12.3 (0.12.3)
---
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```
Going to try the same using Jupyter notebook to rule out the possibility that it is the IJulia kernel.

Also, reconfirming that tabcompletion is not clearing the first few letters after hitting tab. #2929

**Comment by willingc** [comment] 2019-01-17 23:03
Verified that this is an nteract issue and not a IJulia kernel issue by running the same test for Jupyter Classic Notebook.

**Comment by willingc** [comment] 2019-01-17 23:20
<img width="805" alt="screenshot 2019-01-17 15 18 26" src="https://user-images.githubusercontent.com/2680980/51355266-777cc800-1a6b-11e9-8eb9-f2647a3c6009.png">

**Comment by captainsafia** [comment] 2019-11-14 01:12
Re-opening this.

This might be related to the slowness seen in the auto-save logic as well. Perhaps there is an issue with our desktop-native saving experience, in particular with the `writeFileObservable` function that is used to save the file to disk.

I'm going to rename this issue to "Lag when saving large notebooks in desktop app" since that explains the issue a bit more clearly.

**Comment by affans** [comment] 2019-12-17 15:54
Has there been any work done on this issue and it it has been resolved?

**Comment by willingc** [comment] 2020-11-17 06:03
I'm unable to reproduce this with nteract v0.26 using a Julia 1.5.3 kernel. Closing as resolved.

<img width="795" alt="Screen Shot 2020-11-16 at 10 02 18 PM" src="https://user-images.githubusercontent.com/2680980/99352412-6fecfc80-2857-11eb-9b56-ec547c054a8f.png">

**Closed as completed by willingc** 2020-11-17 06:03 UTC
Labels: Error UI/UX, pinned, saving, julia
